# frozen_string_literal: true

source "https://rubygems.org"

gem "dotenv-rails", groups: [:development, :test]

gem "rubocop-shopify", require: false

gem "minitest", "~> 5.16"

gem "solargraph", "~> 0.47.2"

gem "rake", "~> 13.0"

gem "faraday", "~> 2.7"
